blueprint:
  name: 存在感知灯控蓝图
  description: 通过人体存在传感器和物理按钮实现智能灯光控制，基于日出日落时间偏移
  domain: automation
  input:
    sensor_entity:
      name: 存在传感器
      description: 持续监测人体存在的二进制传感器
      selector:
        entity:
          domain: binary_sensor
    button_entity:
      name: 物理按钮
      description: 用于手动关闭灯光的无线开关/实体按钮
      selector:
        entity:
          domain: binary_sensor
    light_entity:
      name: 被控灯具
      description: 需要智能控制的照明设备（可多选）
      selector:
        entity:
          domain: light
          multiple: true
    sunset_offset:
      name: 日落后偏移时间
      description: 日落后多少小时允许开灯（正值表示日落后，负值表示日落前）
      default: 0.5
      selector:
        number:
          min: -12
          max: 12
          step: 0.5
          unit_of_measurement: hours
    sunrise_offset:
      name: 日出前偏移时间
      description: 日出前多少小时允许开灯（正值表示日出后，负值表示日出前）
      default: -0.5
      selector:
        number:
          min: -12
          max: 12
          step: 0.5
          unit_of_measurement: hours

trigger:
  - platform: state
    entity_id: !input sensor_entity
    from: 'off'
    to: 'on'
    id: sensor_trigger
  - platform: state
    entity_id: !input button_entity
    from: 'off'
    to: 'on'
    id: button_trigger

variables:
  sunset_offset: !input sunset_offset
  sunrise_offset: !input sunrise_offset
  sunrise_time: "{{ as_timestamp(state_attr('sun.sun', 'next_rising')) }}"
  sunset_time: "{{ as_timestamp(state_attr('sun.sun', 'next_setting')) }}"
  sunset_target_time: "{{ sunset_time + (sunset_offset * 3600) }}"
  sunrise_target_time: "{{ sunrise_time + (sunrise_offset * 3600) }}"
  current_time: "{{ now().timestamp() }}"
  # 添加用于防抖的变量
  last_trigger_time: "{{ state_attr('automation.' + automation_id, 'last_triggered') | default(0) }}"
  time_since_last_trigger: "{{ (current_time - as_timestamp(last_trigger_time)) if last_trigger_time != 0 else 9999 }}"

action:
  - choose:
      # 存在感知开灯逻辑（带60秒防抖）
      - conditions:
          - condition: state
            entity_id: !input sensor_entity
            state: 'on'
          - condition: state
            entity_id: !input light_entity
            state: 'off'
          - condition: template
            value_template: "{{ current_time >= sunset_target_time or current_time <= sunrise_target_time }}"
          - condition: template
            value_template: "{{ time_since_last_trigger > 60 }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_entity

      # 物理按钮关灯逻辑（带60秒防抖）
      - conditions:
          - condition: trigger
            id: button_trigger
          - condition: template
            value_template: "{{ time_since_last_trigger > 60 }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input light_entity
